import path from "node:path";
import { HTTPException } from "hono/http-exception";
import {
  AppBlueprintModel,
  GeneratedAppModel,
  SpecificationModel,
  type GeneratedAppDocument,
} from "@bismo/db-models";
import type { CreateGeneratedAppInput } from "@bismo/shared-schemas";
import { env } from "../../config/env";
import { archiveCommitToBuffer, initRepoWithCommit, listCommits } from "../../lib/gitRepo";

function repoDir(generatedAppId: string) {
  return path.join(env.GENERATED_APPS_DIR, generatedAppId);
}

export async function serializeGeneratedApp(doc: GeneratedAppDocument) {
  const blueprint = await AppBlueprintModel.findById(doc.blueprintId).select("name");
  return {
    id: String(doc._id),
    blueprintId: String(doc.blueprintId),
    blueprintName: blueprint?.name ?? "",
    database: doc.database,
    frontendFramework: doc.frontendFramework,
    status: doc.status,
    createdBy: String(doc.createdBy),
    createdAt: doc.createdAt.toISOString(),
    updatedAt: doc.updatedAt.toISOString(),
  };
}

/**
 * Resolves everything a real generator will need to read: the blueprint's
 * connected domains/model/org context plus every Specification across them
 * and the blueprint's own. Milestone 1's placeholder generator ignores the
 * result — this only proves the lookup is correct ahead of a real one.
 */
export async function buildBlueprintBundle(blueprintId: string) {
  const blueprint = await AppBlueprintModel.findById(blueprintId);
  if (!blueprint) throw new HTTPException(404, { message: "Blueprint not found" });

  const [domainSpecs, modelSpecs, orgContextSpecs, blueprintSpecs] = await Promise.all([
    SpecificationModel.find({
      parentType: "BusinessDomain",
      parentId: { $in: blueprint.connections.domainIds },
    }),
    blueprint.connections.modelId
      ? SpecificationModel.find({ parentType: "BusinessModel", parentId: blueprint.connections.modelId })
      : Promise.resolve([]),
    blueprint.connections.orgContextId
      ? SpecificationModel.find({ parentType: "OrgContext", parentId: blueprint.connections.orgContextId })
      : Promise.resolve([]),
    SpecificationModel.find({ parentType: "AppBlueprint", parentId: blueprint._id }),
  ]);

  return { blueprint, specs: [...domainSpecs, ...modelSpecs, ...orgContextSpecs, ...blueprintSpecs] };
}

export async function createGeneratedApp(input: CreateGeneratedAppInput, platformUserId: string) {
  const blueprint = await AppBlueprintModel.findById(input.blueprintId);
  if (!blueprint || blueprint.status !== "approved") {
    throw new HTTPException(404, { message: "Blueprint not found" });
  }

  const existing = await GeneratedAppModel.findOne({
    blueprintId: input.blueprintId,
    createdBy: platformUserId,
  });
  if (existing) {
    throw new HTTPException(409, { message: "You've already generated an app from this blueprint" });
  }

  await buildBlueprintBundle(input.blueprintId);

  const doc = await GeneratedAppModel.create({
    blueprintId: input.blueprintId,
    createdBy: platformUserId,
    database: input.database,
    frontendFramework: input.frontendFramework || "React + Vite + TanStack Query",
  });

  const packageName = blueprint.namespace.replace("/", "-");
  await initRepoWithCommit(
    repoDir(String(doc._id)),
    {
      "README.md": `# ${blueprint.name}\n\nGenerated by BISMO (placeholder — Milestone 1 proof of concept; real code generation lands in a future milestone).\n\nDatabase: ${doc.database}\nFrontend: ${doc.frontendFramework}\n`,
      "package.json": `${JSON.stringify({ name: packageName, version: "0.1.0", private: true }, null, 2)}\n`,
    },
    "Initial scaffold (placeholder — Milestone 1)",
  );

  return doc;
}

function assertOwnsGeneratedApp(doc: GeneratedAppDocument, platformUserId: string) {
  // 404, not 403 — a platform user shouldn't learn that another user's
  // generated app exists at all.
  if (String(doc.createdBy) !== platformUserId) {
    throw new HTTPException(404, { message: "Generated app not found" });
  }
}

export async function listMyGeneratedApps(platformUserId: string) {
  const docs = await GeneratedAppModel.find({ createdBy: platformUserId }).sort({ createdAt: -1 });
  return Promise.all(docs.map(serializeGeneratedApp));
}

export async function getGeneratedApp(id: string, platformUserId: string) {
  const doc = await GeneratedAppModel.findById(id);
  if (!doc) throw new HTTPException(404, { message: "Generated app not found" });
  assertOwnsGeneratedApp(doc, platformUserId);
  return doc;
}

export async function listVersions(id: string, platformUserId: string) {
  await getGeneratedApp(id, platformUserId);
  return listCommits(repoDir(id));
}

export async function downloadVersion(id: string, sha: string, platformUserId: string) {
  await getGeneratedApp(id, platformUserId);
  const commits = await listCommits(repoDir(id));
  if (!commits.some((commit) => commit.sha === sha)) {
    throw new HTTPException(404, { message: "Version not found" });
  }
  return archiveCommitToBuffer(repoDir(id), sha);
}
